using System.Collections.Generic;
using System.Globalization;

namespace RcloneFileWatcherCore.Web.Localization
{
    /// <summary>
    /// Minimal translation lookup keyed by the current UI culture (set by RequestLocalization
    /// from the culture cookie). English is the default/fallback; Polish is the second language.
    /// Add a language by adding a dictionary here and an option to the supported cultures.
    /// </summary>
    public class Loc
    {
        public string this[string key]
        {
            get
            {
                var lang = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
                if (Tables.TryGetValue(lang, out var table) && table.TryGetValue(key, out var value))
                    return value;
                return Tables["en"].TryGetValue(key, out var en) ? en : key;
            }
        }

        public string F(string key, params object[] args) => string.Format(this[key], args);

        private static readonly Dictionary<string, Dictionary<string, string>> Tables = new()
        {
            ["en"] = new Dictionary<string, string>
            {
                ["nav.dashboard"] = "Dashboard",
                ["nav.config"] = "Configuration",
                ["nav.rclone"] = "Rclone",
                ["nav.logs"] = "Logs",
                ["nav.logout"] = "Log out",
                ["theme.toggle"] = "Light/dark theme",

                ["dash.watcher"] = "Watcher",
                ["dash.running"] = "Running",
                ["dash.stopped"] = "Stopped",
                ["dash.queued"] = "Queued changes",
                ["dash.watchedPaths"] = "Watched paths",
                ["dash.startedUtc"] = "Started (UTC)",
                ["dash.watchedDirs"] = "Watched directories",
                ["dash.noPaths"] = "No watched paths configured yet.",
                ["dash.startWatcher"] = "Start watcher",
                ["dash.stopWatcher"] = "Stop watcher",
                ["dash.syncNow"] = "Sync now",
                ["dash.fullSync"] = "Full sync",
                ["dash.loading"] = "Loading status…",
                ["dash.msgStarted"] = "Watcher started.",
                ["dash.msgStopped"] = "Watcher stopped.",
                ["dash.msgStartFailed"] = "Could not start: {0}",
                ["dash.msgSyncRequested"] = "Sync requested (check Logs).",
                ["dash.msgFullSyncRequested"] = "Full sync requested (check Logs).",

                ["cfg.intro"] = "Changes are saved to {0} and applied live (the watcher is reloaded). Changing LogPath requires a restart.",
                ["cfg.general"] = "General",
                ["cfg.logLevel"] = "Log level",
                ["cfg.logPath"] = "Log file path (empty = console)",
                ["cfg.syncInterval"] = "Sync interval (s)",
                ["cfg.fullSyncDaily"] = "Full sync daily at (HH:mm)",
                ["cfg.fullSyncStartup"] = "Full sync at startup",
                ["cfg.fullSyncScript"] = "Full sync script",
                ["cfg.autoUpdate"] = "rclone auto-update",
                ["cfg.enableAutoUpdate"] = "Enable auto-update",
                ["cfg.rclonePath"] = "rclone path",
                ["cfg.checkEvery"] = "Check every (h)",
                ["cfg.watchedPaths"] = "Watched paths ({0})",
                ["cfg.importScripts"] = "Import scripts → managed",
                ["cfg.addPath"] = "+ Add path",
                ["cfg.noPaths"] = "No paths. Add at least one for the watcher to monitor.",
                ["cfg.pathN"] = "Path #{0}",
                ["cfg.remove"] = "Remove",
                ["cfg.watchDir"] = "Watched directory",
                ["cfg.includeFromFile"] = "--include-from file",
                ["cfg.runMode"] = "rclone run mode",
                ["cfg.modeScript"] = "Script (.bat/.sh)",
                ["cfg.modeManaged"] = "Managed (command)",
                ["cfg.scriptFile"] = "rclone script (.bat/.sh)",
                ["cfg.importThisScript"] = "Import this script to managed",
                ["cfg.cmdSource"] = "Source",
                ["cfg.cmdDest"] = "Destination (remote:path)",
                ["cfg.cmdCommand"] = "Command",
                ["cfg.includeFromInject"] = "Inject --include-from",
                ["cfg.extraArgs"] = "Extra arguments (one token per line)",
                ["cfg.preview"] = "Command preview:",
                ["cfg.runtimeVars"] = "Variables substituted at run time:",
                ["cfg.exclude"] = "Exclusions (one per line)",
                ["cfg.save"] = "Save & apply",
                ["cfg.reset"] = "Reset",
                ["cfg.savedApplied"] = "Configuration saved and applied.",
                ["cfg.restored"] = "Current configuration restored.",
                ["cfg.notSaved"] = "Not saved — fix the errors below.",
                ["cfg.saveError"] = "Save error: {0}",
                ["cfg.importedOne"] = "Imported the command from the script for path #{0}. Review the fields and save.",
                ["cfg.scriptNotFound"] = "Script not found: {0}",
                ["cfg.noPathPlaceholder"] = "(no path)",
                ["cfg.importError"] = "Import error: {0}",
                ["cfg.importedMany"] = "Imported {0} script(s) to managed. Review the fields and save.",
                ["cfg.importedManySkipped"] = "Imported {0} script(s) to managed, skipped {1} (missing file or error). Review the fields and save.",
                ["cfg.vInterval"] = "Sync interval must be at least 1 second.",
                ["cfg.vTime"] = "Daily full sync time must be in HH:mm format (e.g. 05:30).",
                ["cfg.vStartupScript"] = "Full sync at startup is enabled but no script is set.",
                ["cfg.vRclonePath"] = "rclone auto-update is enabled but no rclone path is set.",
                ["cfg.vCheckHours"] = "Update check frequency cannot be negative.",
                ["cfg.vWatchDir"] = "Path #{0}: watched directory is required.",
                ["cfg.vIncludeFrom"] = "Path #{0}: --include-from file is required.",

                ["rcl.intro"] = "Preview of the rclone invocation for each watched path. Editing is done under Configuration. In Managed mode the command is built from fields (with automatic --include-from); in Script mode the given .bat/.sh file is run.",
                ["rcl.managed"] = "Managed",
                ["rcl.script"] = "Script",
                ["rcl.noCommand"] = "Managed mode without a configured command.",
                ["rcl.scriptLabel"] = "Script:",
                ["rcl.notSet"] = "— (not set)",
                ["rcl.noPaths"] = "No configured paths.",

                ["log.level"] = "Level:",
                ["log.all"] = "All",
                ["log.autoScroll"] = "Auto-scroll",
                ["log.entries"] = "{0} / {1} entries",
                ["log.clear"] = "Clear view",
                ["log.noEntries"] = "(no entries)",

                ["login.password"] = "Password",
                ["login.submit"] = "Log in",
                ["login.wrong"] = "Wrong password.",
            },
            ["pl"] = new Dictionary<string, string>
            {
                ["nav.dashboard"] = "Pulpit",
                ["nav.config"] = "Konfiguracja",
                ["nav.rclone"] = "Rclone",
                ["nav.logs"] = "Logi",
                ["nav.logout"] = "Wyloguj",
                ["theme.toggle"] = "Jasny/ciemny motyw",

                ["dash.watcher"] = "Watcher",
                ["dash.running"] = "Działa",
                ["dash.stopped"] = "Zatrzymany",
                ["dash.queued"] = "Zmiany w kolejce",
                ["dash.watchedPaths"] = "Obserwowane ścieżki",
                ["dash.startedUtc"] = "Uruchomiono (UTC)",
                ["dash.watchedDirs"] = "Obserwowane katalogi",
                ["dash.noPaths"] = "Brak skonfigurowanych ścieżek.",
                ["dash.startWatcher"] = "Uruchom watcher",
                ["dash.stopWatcher"] = "Zatrzymaj watcher",
                ["dash.syncNow"] = "Synchronizuj teraz",
                ["dash.fullSync"] = "Pełna synchronizacja",
                ["dash.loading"] = "Ładowanie statusu…",
                ["dash.msgStarted"] = "Watcher uruchomiony.",
                ["dash.msgStopped"] = "Watcher zatrzymany.",
                ["dash.msgStartFailed"] = "Nie udało się uruchomić: {0}",
                ["dash.msgSyncRequested"] = "Zlecono synchronizację (sprawdź Logi).",
                ["dash.msgFullSyncRequested"] = "Zlecono pełną synchronizację (sprawdź Logi).",

                ["cfg.intro"] = "Zmiany zapisywane są do {0} i stosowane na żywo (watcher zostaje przeładowany). Zmiana LogPath wymaga restartu aplikacji.",
                ["cfg.general"] = "Ogólne",
                ["cfg.logLevel"] = "Poziom logowania",
                ["cfg.logPath"] = "Ścieżka logu (puste = konsola)",
                ["cfg.syncInterval"] = "Interwał synchronizacji (s)",
                ["cfg.fullSyncDaily"] = "Pełna synchronizacja codziennie o (HH:mm)",
                ["cfg.fullSyncStartup"] = "Pełna synchronizacja przy starcie",
                ["cfg.fullSyncScript"] = "Skrypt pełnej synchronizacji",
                ["cfg.autoUpdate"] = "Auto-aktualizacja rclone",
                ["cfg.enableAutoUpdate"] = "Włącz auto-aktualizację",
                ["cfg.rclonePath"] = "Ścieżka do rclone",
                ["cfg.checkEvery"] = "Sprawdzaj co (godz.)",
                ["cfg.watchedPaths"] = "Obserwowane ścieżki ({0})",
                ["cfg.importScripts"] = "Importuj skrypty → Managed",
                ["cfg.addPath"] = "+ Dodaj ścieżkę",
                ["cfg.noPaths"] = "Brak ścieżek. Dodaj przynajmniej jedną, aby watcher coś obserwował.",
                ["cfg.pathN"] = "Ścieżka #{0}",
                ["cfg.remove"] = "Usuń",
                ["cfg.watchDir"] = "Katalog obserwowany",
                ["cfg.includeFromFile"] = "Plik --include-from",
                ["cfg.runMode"] = "Tryb uruchomienia rclone",
                ["cfg.modeScript"] = "Skrypt (.bat/.sh)",
                ["cfg.modeManaged"] = "Managed (komenda)",
                ["cfg.scriptFile"] = "Skrypt rclone (.bat/.sh)",
                ["cfg.importThisScript"] = "Importuj ten skrypt do trybu Managed",
                ["cfg.cmdSource"] = "Źródło",
                ["cfg.cmdDest"] = "Cel (remote:ścieżka)",
                ["cfg.cmdCommand"] = "Komenda",
                ["cfg.includeFromInject"] = "Wstrzyknij --include-from",
                ["cfg.extraArgs"] = "Dodatkowe argumenty (jeden token na linię)",
                ["cfg.preview"] = "Podgląd komendy:",
                ["cfg.runtimeVars"] = "Zmienne podstawiane przy uruchomieniu:",
                ["cfg.exclude"] = "Wykluczenia (jedno na linię)",
                ["cfg.save"] = "Zapisz i zastosuj",
                ["cfg.reset"] = "Przywróć",
                ["cfg.savedApplied"] = "Zapisano i zastosowano konfigurację.",
                ["cfg.restored"] = "Przywrócono bieżącą konfigurację.",
                ["cfg.notSaved"] = "Nie zapisano — popraw błędy poniżej.",
                ["cfg.saveError"] = "Błąd zapisu: {0}",
                ["cfg.importedOne"] = "Zaimportowano komendę ze skryptu dla ścieżki #{0}. Sprawdź pola i zapisz.",
                ["cfg.scriptNotFound"] = "Nie znaleziono skryptu: {0}",
                ["cfg.noPathPlaceholder"] = "(brak ścieżki)",
                ["cfg.importError"] = "Błąd importu: {0}",
                ["cfg.importedMany"] = "Zaimportowano {0} skrypt(ów) do trybu Managed. Sprawdź pola i zapisz.",
                ["cfg.importedManySkipped"] = "Zaimportowano {0} skrypt(ów) do trybu Managed, pominięto {1} (brak pliku lub błąd). Sprawdź pola i zapisz.",
                ["cfg.vInterval"] = "Interwał synchronizacji musi być co najmniej 1 sekundę.",
                ["cfg.vTime"] = "Godzina pełnej synchronizacji musi mieć format HH:mm (np. 05:30).",
                ["cfg.vStartupScript"] = "Włączono pełną synchronizację przy starcie, ale nie podano skryptu.",
                ["cfg.vRclonePath"] = "Włączono auto-aktualizację rclone, ale nie podano ścieżki do rclone.",
                ["cfg.vCheckHours"] = "Częstotliwość sprawdzania aktualizacji nie może być ujemna.",
                ["cfg.vWatchDir"] = "Ścieżka #{0}: katalog obserwowany jest wymagany.",
                ["cfg.vIncludeFrom"] = "Ścieżka #{0}: plik --include-from jest wymagany.",

                ["rcl.intro"] = "Podgląd wywołania rclone dla każdej obserwowanej ścieżki. Edycja odbywa się w sekcji Konfiguracja. W trybie Managed komenda jest budowana z pól (z automatycznym --include-from); w trybie Skrypt uruchamiany jest podany plik .bat/.sh.",
                ["rcl.managed"] = "Managed",
                ["rcl.script"] = "Skrypt",
                ["rcl.noCommand"] = "Tryb Managed bez skonfigurowanej komendy.",
                ["rcl.scriptLabel"] = "Skrypt:",
                ["rcl.notSet"] = "— (nie ustawiono)",
                ["rcl.noPaths"] = "Brak skonfigurowanych ścieżek.",

                ["log.level"] = "Poziom:",
                ["log.all"] = "Wszystkie",
                ["log.autoScroll"] = "Auto-przewijanie",
                ["log.entries"] = "{0} / {1} wpisów",
                ["log.clear"] = "Wyczyść widok",
                ["log.noEntries"] = "(brak wpisów)",

                ["login.password"] = "Hasło",
                ["login.submit"] = "Zaloguj",
                ["login.wrong"] = "Nieprawidłowe hasło.",
            },
        };
    }
}
